command:
  - "python"
  - "app.py"

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_CATALOG
    value: "serverless_stable_wunnava_catalog"
  - name: USE_MOCK_BACKEND
    value: "true"
